#!/usr/bin/env python
# V_obs = V_ast + alpha * V_RFI + eta
raw:
    input_dir: /data/
    output_dir: ./data/processed
    eta: 0.017 # noise per visibility pixel in Janskys
    alpha: 0.1 # RFI amplitude
    
augmentation:
    alpha: 0.1  # [0.05, 0.1, 0.2, 0.4]
    eta: 0.017 # [0.017, 0.034]
    flip: False
